### ISSUE TITLE
this.target becoming undefined in monsters.ts

### ISSUE THREAD

**Issue by jernaumorat** [jamesmgittins/light-the-way-home#1]
Tested in both Firefox 85.0.2 and Safari 14.0.3 (16610.4.3.1.4), error report from Safari.

When playing, game can lock up at any time. Seems to be persistent in save state, as error reoccurs very quickly after reloading.

So far error has only occurred after purchasing a second light, though this may just be a function of time spent.

```
[Error] TypeError: undefined is not an object (evaluating 'this.target.x')
	updateMonsterSpeed (bundle.js:254:21987) (monsters.ts:161)
	updateMonster (bundle.js:254:20699) (monsters.ts:91)
	rl (bundle.js:254:23389) (application.ts:21)
	al (bundle.js:254:24485) (playerlights.ts:155)
	(anonymous function) (bundle.js:254:27311) (application.ts:99)
	(anonymous function) (bundle.js:75:558) (ticker.es.ts:132)
	(anonymous function) (bundle.js:75:3394) (ticker.es.ts:584)
	(anonymous function) (bundle.js:75:1400) (ticker.es.ts:334)
```

**Comment by jernaumorat** [comment]
Looking at `monsters.ts`, it seems like the Monster object isn't releasing its Human target (once the Human has escaped and has been released) before recalculating trajectory, so trying to hone in on the position of a Human object that doesn't exist.

EDIT: Error still occurs before any humans have yet reached an escape point, I'll keep looking.

**Comment by jamesmgittins** [comment]
I'm not sure what could cause that error. I haven't been able to reproduce it.

I've made a change so the monster will just move to the escape position if the target is undefined when it gets to that part.

**Comment by jernaumorat** [comment]
This appears to have fixed the issue, thanks!
